"""create consultation medicines table

Revision ID: 70dafb73802e
Revises: b1c5ec28ebfe
Create Date: 2026-08-13 23:52:10.117778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dafb73802e'
down_revision: Union[str, Sequence[str], None] = 'b1c5ec28ebfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stock_unit', sa.String(length=30), nullable=False),
    sa.Column('dosage_instruction', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('dispensed_by', sa.Integer(), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_medicines_consultation_id'), 'consultation_medicines', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_consultation_medicines_id'), 'consultation_medicines', ['id'], unique=False)
    op.create_index(op.f('ix_consultation_medicines_medicine_id'), 'consultation_medicines', ['medicine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_medicines_medicine_id'), table_name='consultation_medicines')
    op.drop_index(op.f('ix_consultation_medicines_id'), table_name='consultation_medicines')
    op.drop_index(op.f('ix_consultation_medicines_consultation_id'), table_name='consultation_medicines')
    op.drop_table('consultation_medicines')
    # ### end Alembic commands ###
