"""create medicines table

Revision ID: 87e90bb8c853
Revises: adfdbbc0ab42
Create Date: 2026-08-13 22:59:32.227241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e90bb8c853'
down_revision: Union[str, Sequence[str], None] = 'adfdbbc0ab42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('generic_name', sa.String(length=150), nullable=True),
    sa.Column('dosage_strength', sa.String(length=100), nullable=True),
    sa.Column('dosage_form', sa.String(length=50), nullable=True),
    sa.Column('package_unit', sa.String(length=50), nullable=True),
    sa.Column('dispensing_unit', sa.String(length=50), nullable=False),
    sa.Column('units_per_package', sa.Integer(), nullable=True),
    sa.Column('package_stock', sa.Integer(), nullable=False),
    sa.Column('loose_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_code'), 'medicines', ['code'], unique=True)
    op.create_index(op.f('ix_medicines_id'), 'medicines', ['id'], unique=False)
    op.create_index(op.f('ix_medicines_name'), 'medicines', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicines_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_id'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_code'), table_name='medicines')
    op.drop_table('medicines')
    # ### end Alembic commands ###
