"""add disease id to consultations

Revision ID: adfdbbc0ab42
Revises: 860bcd9cb990
Create Date: 2026-08-13 20:50:30.158439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfdbbc0ab42'
down_revision: Union[str, Sequence[str], None] = '860bcd9cb990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('disease_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_consultations_disease_id'), 'consultations', ['disease_id'], unique=False)
    op.create_foreign_key(None, 'consultations', 'diseases', ['disease_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_index(op.f('ix_consultations_disease_id'), table_name='consultations')
    op.drop_column('consultations', 'disease_id')
    # ### end Alembic commands ###
