"""create patient medical history table

Revision ID: fdc6ba6cce64
Revises: 5f2bb8ee6597
Create Date: 2026-08-13 07:36:03.855255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc6ba6cce64'
down_revision: Union[str, Sequence[str], None] = '5f2bb8ee6597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_medical_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('history_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_medical_histories_id'), 'patient_medical_histories', ['id'], unique=False)
    op.create_index(op.f('ix_patient_medical_histories_patient_id'), 'patient_medical_histories', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_medical_histories_patient_id'), table_name='patient_medical_histories')
    op.drop_index(op.f('ix_patient_medical_histories_id'), table_name='patient_medical_histories')
    op.drop_table('patient_medical_histories')
    # ### end Alembic commands ###
