from sqlalchemy import select

from app.db.session import SessionLocal
from app.models.medicine import Medicine


CANDIDATE_FORMULARY = [{'code': 'MED-AI-001',
  'name': 'Albendazole',
  'generic_name': 'Albendazole',
  'dosage_strength': '400 mg',
  'dosage_form': 'Chewable Tablet',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-002',
  'name': 'Amoxicillin',
  'generic_name': 'Amoxicillin',
  'dosage_strength': '500 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-003',
  'name': 'Azithromycin',
  'generic_name': 'Azithromycin',
  'dosage_strength': '500 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-004',
  'name': 'Cefixime',
  'generic_name': 'Cefixime',
  'dosage_strength': '200 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-005',
  'name': 'Cefuroxime',
  'generic_name': 'Cefuroxime',
  'dosage_strength': '500 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-006',
  'name': 'Ciprofloxacin',
  'generic_name': 'Ciprofloxacin',
  'dosage_strength': '500 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-007',
  'name': 'Clarithromycin',
  'generic_name': 'Clarithromycin',
  'dosage_strength': '500 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-008',
  'name': 'Clindamycin',
  'generic_name': 'Clindamycin',
  'dosage_strength': '300 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-009',
  'name': 'Clotrimazole',
  'generic_name': 'Clotrimazole',
  'dosage_strength': '1%',
  'dosage_form': 'Cream',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tube',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-010',
  'name': 'Cloxacillin',
  'generic_name': 'Cloxacillin',
  'dosage_strength': '500 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-011',
  'name': 'Co-amoxiclav',
  'generic_name': 'Co-amoxiclav',
  'dosage_strength': '500 mg + 125 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-012',
  'name': 'Co-trimoxazole',
  'generic_name': 'Co-trimoxazole',
  'dosage_strength': '800 mg + 160 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-013',
  'name': 'Doxycycline',
  'generic_name': 'Doxycycline',
  'dosage_strength': '100 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-014',
  'name': 'Erythromycin',
  'generic_name': 'Erythromycin',
  'dosage_strength': '500 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-015',
  'name': 'Fluconazole',
  'generic_name': 'Fluconazole',
  'dosage_strength': '150 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-016',
  'name': 'Ketoconazole',
  'generic_name': 'Ketoconazole',
  'dosage_strength': '2%',
  'dosage_form': 'Cream',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tube',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-017',
  'name': 'Mebendazole',
  'generic_name': 'Mebendazole',
  'dosage_strength': '500 mg',
  'dosage_form': 'Chewable Tablet',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-018',
  'name': 'Metronidazole',
  'generic_name': 'Metronidazole',
  'dosage_strength': '500 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-019',
  'name': 'Nitrofurantoin',
  'generic_name': 'Nitrofurantoin',
  'dosage_strength': '100 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-020',
  'name': 'Oseltamivir',
  'generic_name': 'Oseltamivir',
  'dosage_strength': '75 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AI-021',
  'name': 'Tobramycin',
  'generic_name': 'Tobramycin',
  'dosage_strength': '0.3%',
  'dosage_form': 'Ophthalmic Drops',
  'medicine_category': 'ANTI_INFECTIVE',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'bottle',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AT-001',
  'name': 'Clopidogrel',
  'generic_name': 'Clopidogrel',
  'dosage_strength': '75 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_THROMBOTIC',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-AT-002',
  'name': 'Aspirin',
  'generic_name': 'Aspirin',
  'dosage_strength': '80 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_THROMBOTIC',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-RESP-001',
  'name': 'Budesonide + Formoterol',
  'generic_name': 'Budesonide + Formoterol',
  'dosage_strength': '160 mcg + 4.5 mcg/dose',
  'dosage_form': 'Metered-Dose Inhaler',
  'medicine_category': 'ANTI_ASTHMA_COPD',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'inhaler',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-RESP-002',
  'name': 'Fluticasone + Salmeterol',
  'generic_name': 'Fluticasone + Salmeterol',
  'dosage_strength': '125 mcg + 25 mcg/dose',
  'dosage_form': 'Metered-Dose Inhaler',
  'medicine_category': 'ANTI_ASTHMA_COPD',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'inhaler',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-RESP-003',
  'name': 'Ipratropium',
  'generic_name': 'Ipratropium',
  'dosage_strength': '250 mcg/mL, 2 mL',
  'dosage_form': 'Nebule',
  'medicine_category': 'ANTI_ASTHMA_COPD',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'nebule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-RESP-004',
  'name': 'Montelukast',
  'generic_name': 'Montelukast',
  'dosage_strength': '10 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_ASTHMA_COPD',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-RESP-005',
  'name': 'Prednisone',
  'generic_name': 'Prednisone',
  'dosage_strength': '20 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_ASTHMA_COPD',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-RESP-006',
  'name': 'Salbutamol',
  'generic_name': 'Salbutamol',
  'dosage_strength': '1 mg/mL, 2.5 mL',
  'dosage_form': 'Nebule',
  'medicine_category': 'ANTI_ASTHMA_COPD',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'nebule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-RESP-007',
  'name': 'Ipratropium + Salbutamol',
  'generic_name': 'Ipratropium + Salbutamol',
  'dosage_strength': '500 mcg + 2.5 mg / 2.5 mL',
  'dosage_form': 'Nebule',
  'medicine_category': 'ANTI_ASTHMA_COPD',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'nebule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-RESP-008',
  'name': 'Tiotropium',
  'generic_name': 'Tiotropium',
  'dosage_strength': '18 mcg/dose',
  'dosage_form': 'Inhalation Capsule / DPI',
  'medicine_category': 'ANTI_ASTHMA_COPD',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-001',
  'name': 'Aluminum Hydroxide + Magnesium Hydroxide',
  'generic_name': 'Aluminum Hydroxide + Magnesium Hydroxide',
  'dosage_strength': '200 mg + 100 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': False,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-002',
  'name': 'Butamirate',
  'generic_name': 'Butamirate',
  'dosage_strength': '50 mg MR',
  'dosage_form': 'Modified-Release Tablet',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-003',
  'name': 'Celecoxib',
  'generic_name': 'Celecoxib',
  'dosage_strength': '200 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-004',
  'name': 'Cetirizine',
  'generic_name': 'Cetirizine',
  'dosage_strength': '10 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': False,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-005',
  'name': 'Colchicine',
  'generic_name': 'Colchicine',
  'dosage_strength': '500 mcg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-006',
  'name': 'Chlorphenamine',
  'generic_name': 'Chlorphenamine',
  'dosage_strength': '4 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': False,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-007',
  'name': 'Diphenhydramine',
  'generic_name': 'Diphenhydramine',
  'dosage_strength': '50 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': False,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-008',
  'name': 'Ferrous Salt',
  'generic_name': 'Ferrous Salt',
  'dosage_strength': 'equiv. 60 mg elemental iron',
  'dosage_form': 'Tablet',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': False,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-009',
  'name': 'Ferrous Salt + Folic Acid',
  'generic_name': 'Ferrous Salt + Folic Acid',
  'dosage_strength': '60 mg elemental iron + 400 mcg folic acid',
  'dosage_form': 'Tablet',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': False,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-010',
  'name': 'Ibuprofen',
  'generic_name': 'Ibuprofen',
  'dosage_strength': '400 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': False,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-011',
  'name': 'Lagundi (Vitex negundo)',
  'generic_name': 'Lagundi (Vitex negundo)',
  'dosage_strength': '600 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': False,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-012',
  'name': 'Loratadine',
  'generic_name': 'Loratadine',
  'dosage_strength': '10 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': False,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-013',
  'name': 'Mefenamic Acid',
  'generic_name': 'Mefenamic Acid',
  'dosage_strength': '500 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-014',
  'name': 'Naproxen',
  'generic_name': 'Naproxen',
  'dosage_strength': '500 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-015',
  'name': 'Omeprazole',
  'generic_name': 'Omeprazole',
  'dosage_strength': '20 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-016',
  'name': 'Oral Rehydration Salts',
  'generic_name': 'Oral Rehydration Salts',
  'dosage_strength': 'ORS 75-replacement, approximately 5.575 g',
  'dosage_form': 'Sachet',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': False,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'sachet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-017',
  'name': 'Paracetamol',
  'generic_name': 'Paracetamol',
  'dosage_strength': '500 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': False,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-SUP-018',
  'name': 'Zinc',
  'generic_name': 'Zinc',
  'dosage_strength': '20 mg elemental zinc',
  'dosage_form': 'Dispersible Tablet',
  'medicine_category': 'SUPPORTIVE_OTHER',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': False,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-DM-001',
  'name': 'Dapagliflozin',
  'generic_name': 'Dapagliflozin',
  'dosage_strength': '10 mg',
  'dosage_form': 'Film-Coated Tablet',
  'medicine_category': 'ANTI_DIABETIC',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-DM-002',
  'name': 'Gliclazide',
  'generic_name': 'Gliclazide',
  'dosage_strength': '30 mg MR',
  'dosage_form': 'Modified-Release Tablet',
  'medicine_category': 'ANTI_DIABETIC',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-DM-003',
  'name': 'Metformin',
  'generic_name': 'Metformin',
  'dosage_strength': '500 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_DIABETIC',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-LIP-001',
  'name': 'Atorvastatin',
  'generic_name': 'Atorvastatin',
  'dosage_strength': '20 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_DYSLIPIDEMIA',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-LIP-002',
  'name': 'Fenofibrate',
  'generic_name': 'Fenofibrate',
  'dosage_strength': '160 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_DYSLIPIDEMIA',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-LIP-003',
  'name': 'Rosuvastatin',
  'generic_name': 'Rosuvastatin',
  'dosage_strength': '20 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_DYSLIPIDEMIA',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-LIP-004',
  'name': 'Simvastatin',
  'generic_name': 'Simvastatin',
  'dosage_strength': '20 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_DYSLIPIDEMIA',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-001',
  'name': 'Amlodipine',
  'generic_name': 'Amlodipine',
  'dosage_strength': '5 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-002',
  'name': 'Atenolol',
  'generic_name': 'Atenolol',
  'dosage_strength': '50 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-003',
  'name': 'Captopril',
  'generic_name': 'Captopril',
  'dosage_strength': '25 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-004',
  'name': 'Clonidine',
  'generic_name': 'Clonidine',
  'dosage_strength': '75 mcg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-005',
  'name': 'Diltiazem',
  'generic_name': 'Diltiazem',
  'dosage_strength': '60 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-006',
  'name': 'Enalapril',
  'generic_name': 'Enalapril',
  'dosage_strength': '5 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-007',
  'name': 'Enalapril + Hydrochlorothiazide',
  'generic_name': 'Enalapril + Hydrochlorothiazide',
  'dosage_strength': '10 mg + 25 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-008',
  'name': 'Hydrochlorothiazide',
  'generic_name': 'Hydrochlorothiazide',
  'dosage_strength': '25 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-009',
  'name': 'Isosorbide Dinitrate',
  'generic_name': 'Isosorbide Dinitrate',
  'dosage_strength': '5 mg',
  'dosage_form': 'Sublingual Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-010',
  'name': 'Isosorbide Mononitrate',
  'generic_name': 'Isosorbide Mononitrate',
  'dosage_strength': '30 mg MR',
  'dosage_form': 'Modified-Release Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-011',
  'name': 'Losartan',
  'generic_name': 'Losartan',
  'dosage_strength': '50 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-012',
  'name': 'Methyldopa',
  'generic_name': 'Methyldopa',
  'dosage_strength': '250 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-013',
  'name': 'Metoprolol',
  'generic_name': 'Metoprolol',
  'dosage_strength': '50 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-014',
  'name': 'Tamsulosin',
  'generic_name': 'Tamsulosin',
  'dosage_strength': '200 mcg',
  'dosage_form': 'Capsule',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-015',
  'name': 'Telmisartan',
  'generic_name': 'Telmisartan',
  'dosage_strength': '40 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-016',
  'name': 'Telmisartan + Hydrochlorothiazide',
  'generic_name': 'Telmisartan + Hydrochlorothiazide',
  'dosage_strength': '40 mg + 12.5 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-017',
  'name': 'Valsartan',
  'generic_name': 'Valsartan',
  'dosage_strength': '80 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-CV-018',
  'name': 'Valsartan + Hydrochlorothiazide',
  'generic_name': 'Valsartan + Hydrochlorothiazide',
  'dosage_strength': '80 mg + 12.5 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'ANTI_HYPERTENSIVE_CARDIOLOGY',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-NS-001',
  'name': 'Gabapentin',
  'generic_name': 'Gabapentin',
  'dosage_strength': '300 mg',
  'dosage_form': 'Capsule',
  'medicine_category': 'NERVOUS_SYSTEM',
  'formulary_status': 'CANDIDATE',
  'program_type': None,
  'requires_prescription': True,
  'restricted_dispensing': False,
  'sensitive_inventory': False,
  'forecast_enabled': True,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'capsule',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-TB-001',
  'name': 'Rifampicin + Isoniazid + Pyrazinamide + Ethambutol',
  'generic_name': 'Rifampicin + Isoniazid + Pyrazinamide + Ethambutol',
  'dosage_strength': '150 mg + 75 mg + 400 mg + 275 mg',
  'dosage_form': 'Fixed-Dose Combination Tablet',
  'medicine_category': 'SENSITIVE_PROGRAM',
  'formulary_status': 'CANDIDATE',
  'program_type': 'TB',
  'requires_prescription': True,
  'restricted_dispensing': True,
  'sensitive_inventory': True,
  'forecast_enabled': False,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-TB-002',
  'name': 'Rifampicin + Isoniazid',
  'generic_name': 'Rifampicin + Isoniazid',
  'dosage_strength': '150 mg + 75 mg',
  'dosage_form': 'Fixed-Dose Combination Tablet',
  'medicine_category': 'SENSITIVE_PROGRAM',
  'formulary_status': 'CANDIDATE',
  'program_type': 'TB',
  'requires_prescription': True,
  'restricted_dispensing': True,
  'sensitive_inventory': True,
  'forecast_enabled': False,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-TB-003',
  'name': 'Isoniazid',
  'generic_name': 'Isoniazid',
  'dosage_strength': '300 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SENSITIVE_PROGRAM',
  'formulary_status': 'CANDIDATE',
  'program_type': 'TB',
  'requires_prescription': True,
  'restricted_dispensing': True,
  'sensitive_inventory': True,
  'forecast_enabled': False,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-HIV-001',
  'name': 'Tenofovir DF + Lamivudine + Dolutegravir',
  'generic_name': 'Tenofovir DF + Lamivudine + Dolutegravir',
  'dosage_strength': '300 mg + 300 mg + 50 mg',
  'dosage_form': 'Film-Coated Fixed-Dose Combination Tablet',
  'medicine_category': 'SENSITIVE_PROGRAM',
  'formulary_status': 'CANDIDATE',
  'program_type': 'HIV',
  'requires_prescription': True,
  'restricted_dispensing': True,
  'sensitive_inventory': True,
  'forecast_enabled': False,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-HIV-002',
  'name': 'Dolutegravir',
  'generic_name': 'Dolutegravir',
  'dosage_strength': '50 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SENSITIVE_PROGRAM',
  'formulary_status': 'CANDIDATE',
  'program_type': 'HIV',
  'requires_prescription': True,
  'restricted_dispensing': True,
  'sensitive_inventory': True,
  'forecast_enabled': False,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-HIV-003',
  'name': 'Tenofovir DF',
  'generic_name': 'Tenofovir DF',
  'dosage_strength': '300 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SENSITIVE_PROGRAM',
  'formulary_status': 'CANDIDATE',
  'program_type': 'HIV',
  'requires_prescription': True,
  'restricted_dispensing': True,
  'sensitive_inventory': True,
  'forecast_enabled': False,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-HIV-004',
  'name': 'Abacavir',
  'generic_name': 'Abacavir',
  'dosage_strength': '300 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SENSITIVE_PROGRAM',
  'formulary_status': 'CANDIDATE',
  'program_type': 'HIV',
  'requires_prescription': True,
  'restricted_dispensing': True,
  'sensitive_inventory': True,
  'forecast_enabled': False,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-HIV-005',
  'name': 'Lopinavir + Ritonavir',
  'generic_name': 'Lopinavir + Ritonavir',
  'dosage_strength': '200 mg + 50 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SENSITIVE_PROGRAM',
  'formulary_status': 'CANDIDATE',
  'program_type': 'HIV',
  'requires_prescription': True,
  'restricted_dispensing': True,
  'sensitive_inventory': True,
  'forecast_enabled': False,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-STI-001',
  'name': 'Benzathine Penicillin G',
  'generic_name': 'Benzathine Penicillin G',
  'dosage_strength': '1,200,000 units',
  'dosage_form': 'Injection Vial',
  'medicine_category': 'SENSITIVE_PROGRAM',
  'formulary_status': 'CANDIDATE',
  'program_type': 'STI',
  'requires_prescription': True,
  'restricted_dispensing': True,
  'sensitive_inventory': True,
  'forecast_enabled': False,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'vial',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-STI-002',
  'name': 'Ceftriaxone',
  'generic_name': 'Ceftriaxone',
  'dosage_strength': '1 g',
  'dosage_form': 'Injection Vial',
  'medicine_category': 'SENSITIVE_PROGRAM',
  'formulary_status': 'CANDIDATE',
  'program_type': 'STI',
  'requires_prescription': True,
  'restricted_dispensing': True,
  'sensitive_inventory': True,
  'forecast_enabled': False,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'vial',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True},
 {'code': 'MED-STI-003',
  'name': 'Acyclovir',
  'generic_name': 'Acyclovir',
  'dosage_strength': '800 mg',
  'dosage_form': 'Tablet',
  'medicine_category': 'SENSITIVE_PROGRAM',
  'formulary_status': 'CANDIDATE',
  'program_type': 'STI',
  'requires_prescription': True,
  'restricted_dispensing': True,
  'sensitive_inventory': True,
  'forecast_enabled': False,
  'stock_verified': False,
  'package_unit': None,
  'dispensing_unit': 'tablet',
  'units_per_package': None,
  'package_stock': 0,
  'loose_stock': 0,
  'reorder_level': 0,
  'is_active': True}]


def seed_medicine_formulary():
    db = SessionLocal()

    created = 0
    corrected = 0

    try:
        for item in CANDIDATE_FORMULARY:
            medicine = db.scalar(
                select(Medicine).where(
                    Medicine.code
                    == item["code"]
                )
            )

            if medicine is None:
                medicine = Medicine(
                    **item
                )

                db.add(medicine)
                created += 1
                continue

            # Correct / refresh candidate metadata.
            # Existing actual stock quantities, reorder levels,
            # activation state, formulary verification and stock
            # verification are preserved.
            for field in [
                "name",
                "generic_name",
                "dosage_strength",
                "dosage_form",
                "medicine_category",
                "program_type",
                "requires_prescription",
                "restricted_dispensing",
                "sensitive_inventory",
                "forecast_enabled",
                "dispensing_unit",
            ]:
                setattr(
                    medicine,
                    field,
                    item[field],
                )

            corrected += 1

        db.commit()

        print(
            "Medicine candidate formulary metadata "
            "correction complete."
        )

        print(
            f"  Created: {created}"
        )

        print(
            f"  Corrected existing candidate rows: {corrected}"
        )

        print(
            "  Stock quantities and verification state "
            "were preserved."
        )

    except Exception:
        db.rollback()
        raise

    finally:
        db.close()


if __name__ == "__main__":
    seed_medicine_formulary()
